version: "3.9"

services:
  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - CLI_ARGS= #optional
    volumes:
      - ${HDD_PATH}/duplicati/config:/config
      - ${HDD_PATH}/duplicati/backups:/backups
      - ${HDD_PATH}/duplicati/source:/source
    ports:
      - 8200:8200
    restart: unless-stopped
  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${HDD_PATH}/syncthing/config:/config
      - ${HDD_PATH}/duplicati/source:/duplicati-source
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
